# Generated by Django 5.0.1 on 2024-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("desc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="experts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("address", models.TextField()),
                ("phone_number", models.IntegerField()),
                ("email_id", models.EmailField(max_length=254)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="latest_news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("date", models.DateField()),
                ("location", models.TextField()),
                ("writer", models.CharField(max_length=30)),
                ("image", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
        migrations.CreateModel(
            name="tutorials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("videos", models.FileField(upload_to="")),
            ],
        ),
    ]
