# Generated by Django 5.0.1 on 2024-02-08 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_blogs_experts_faq_latest_news_tutorials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="desc",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
