# Generated by Django 5.0.1 on 2024-02-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_alter_blogs_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="latest_news",
            name="headline",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tutorials",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
