# Generated by Django 5.0.1 on 2024-02-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_alter_blogs_title_alter_latest_news_headline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experts",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
