# Generated by Django 5.0.1 on 2024-02-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_alter_experts_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="experts",
            name="image",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="latest_news",
            name="image",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
