# Generated by Django 5.0.1 on 2024-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0006_alter_blogs_image_alter_experts_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="latest_news",
            name="headline",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tutorials",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
