# Generated by Django 5.0.1 on 2024-02-09 09:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0007_alter_blogs_title_alter_latest_news_headline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latest_news",
            name="desc",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
