# Generated by Django 5.0.1 on 2024-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0011_userregister"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testid", models.CharField(max_length=10)),
                ("testname", models.CharField(max_length=10)),
            ],
        ),
    ]
