# Generated by Django 5.0.1 on 2024-02-17 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0012_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="test",
        ),
    ]
