# Generated by Django 5.0.1 on 2024-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0013_delete_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="age",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="birthday",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="gender",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="pincode",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="state",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
