# Generated by Django 5.0.1 on 2024-02-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0015_userregister_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregister",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
