# Generated by Django 5.0.1 on 2024-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0016_alter_userregister_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.TextField()),
                ("price", models.TextField()),
            ],
        ),
    ]
