# Generated by Django 5.0.1 on 2024-03-06 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0017_form"),
    ]

    operations = [
        migrations.DeleteModel(
            name="form",
        ),
    ]
